# Minimal tmux configuration
set -g mouse on
set -g history-limit 10000

# use C-a as prefix (optional)
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g status-interval 5
set -g status-left "#(whoami)@#H"
