# Terminal
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Mouse
set -g mouse on

# History
set -g history-limit 100000

# Faster escape
set -sg escape-time 10

# Numbering
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# Better splits
unbind %
unbind '"'
bind | split-window -h
bind - split-window -v

# Vim-like pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Reload config
bind r source-file ~/.tmux.conf \; display-message "Configuration reloaded."
